name: cenv
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - aom=3.12.1=h7934f7d_0
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - cairo=1.18.0=hbb29018_2
  - cpython=3.11.14=py311hd8ed1ab_2
  - dav1d=1.2.1=hd590300_0
  - expat=2.7.3=h3385a95_0
  - ffmpeg=6.1.1=hecf7045_5
  - filelock=3.20.0=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h2c49b7f_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=hc364b38_1
  - freetype=2.14.1=ha770c72_0
  - fribidi=1.0.16=hb03c661_0
  - fsspec=2025.10.0=pyhd8ed1ab_0
  - gettext=0.25.1=h3f43e3d_1
  - gettext-tools=0.25.1=h3f43e3d_1
  - giflib=5.2.2=hd590300_0
  - gmp=6.3.0=hac33072_2
  - gmpy2=2.2.1=py311h92a432a_2
  - graphite2=1.3.14=hecca717_2
  - harfbuzz=10.2.0=hdfddeaa_1
  - icu=73.2=h59595ed_0
  - jinja2=3.1.6=pyhd8ed1ab_0
  - jpeg=9e=h0b41bf4_3
  - lame=3.100=h7b6447c_0
  - lcms2=2.16=h92b89f2_1
  - ld_impl_linux-64=2.44=h153f514_2
  - leptonica=1.82.0=hfdeec58_3
  - lerc=4.0.0=h0aef613_1
  - libabseil=20240722.0=cxx17_hbbce691_4
  - libarchive=3.8.2=h3ec8f01_0
  - libasprintf=0.25.1=h3f43e3d_1
  - libasprintf-devel=0.25.1=h3f43e3d_1
  - libavif=1.1.1=h0131e85_1
  - libblas=3.11.0=1_h4a7cf45_openblas
  - libcblas=3.11.0=1_h0358290_openblas
  - libdeflate=1.22=hb9d3cd8_0
  - libffi=3.4.4=h6a678d5_1
  - libflac=1.4.3=h59595ed_0
  - libfreetype=2.14.1=ha770c72_0
  - libfreetype6=2.14.1=h73754d4_0
  - libgcc=15.2.0=h69a1729_7
  - libgcc-ng=15.2.0=h166f726_7
  - libgettextpo=0.25.1=h3f43e3d_1
  - libgettextpo-devel=0.25.1=h3f43e3d_1
  - libgfortran=15.2.0=h69a702a_7
  - libgfortran5=15.2.0=hcd61629_7
  - libglib=2.84.0=h2ff4ddf_0
  - libgomp=15.2.0=h4751f2c_7
  - libiconv=1.18=h3b78370_2
  - liblapack=3.11.0=1_h47877c9_openblas
  - libnsl=2.0.0=h5eee18b_0
  - libogg=1.3.5=h27cfd23_1
  - libopenblas=0.3.30=pthreads_h94d23a6_4
  - libopenjpeg=2.5.4=hee96239_1
  - libopus=1.3.1=h5eee18b_1
  - libpng=1.6.50=h2ed474d_0
  - libprotobuf=5.28.3=h6128344_1
  - libsndfile=1.2.2=hc60ed4a_1
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libtheora=1.2.0=h32ad74f_1
  - libtiff=4.7.0=hde9077f_0
  - libtorch=2.5.1=cpu_generic_h90be84d_13
  - libuuid=1.41.5=h5eee18b_0
  - libuv=1.51.0=hb03c661_1
  - libvorbis=1.3.7=h7b6447c_0
  - libvpx=1.15.2=hecca717_0
  - libwebp=1.3.2=h9f374a3_1
  - libwebp-base=1.3.2=hd590300_1
  - libxcb=1.17.0=h9b100fa_0
  - libxml2=2.13.9=h2c43086_0
  - libzlib=1.3.1=hb25bd0a_0
  - lz4-c=1.9.4=hcb278e6_0
  - mad=0.15.1b=h9c3ff4c_1
  - markupsafe=3.0.3=py311h3778330_0
  - mpc=1.3.1=h24ddda3_1
  - mpfr=4.2.1=h90cbb55_3
  - mpg123=1.32.9=hc50e24c_0
  - mpmath=1.3.0=pyhd8ed1ab_1
  - ncurses=6.5=h7934f7d_0
  - networkx=3.5=pyhe01879c_0
  - nomkl=1.0=h5ca1d4c_0
  - numpy=2.3.5=py311h2e04523_0
  - openh264=2.6.0=hc22cd8d_0
  - openjpeg=2.5.3=h55fea9a_1
  - openssl=3.6.0=h26f9b46_0
  - pcre2=10.44=hc749103_2
  - pillow=12.0.0=py311h3b88751_1
  - pip=25.3=pyhc872135_0
  - pixman=0.46.4=h54a6638_1
  - pthread-stubs=0.3=h0ce48e5_1
  - pybind11=3.0.1=pyh7a1b43c_0
  - pybind11-global=3.0.1=pyhc7ab6ef_0
  - python=3.11.14=h6fa692b_0
  - python_abi=3.11=2_cp311
  - pytorch=2.5.1=cpu_generic_py311_h36b4074_13
  - readline=8.3=hc2a1206_0
  - setuptools=80.9.0=py311h06a4308_0
  - sleef=3.9.0=ha0421bc_0
  - sox=14.4.2=h32e7c5b_1019
  - sqlite=3.51.0=h2a70700_0
  - sympy=1.14.0=pyh2585a3b_105
  - tesseract=5.2.0=hb0d2e87_3
  - tk=8.6.15=h54e0aa7_0
  - torchaudio=2.5.1=py311ha02d727_0
  - torchvision=0.20.1=cpu_py311h1c79344_2
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025b=h04d1e81_0
  - wheel=0.45.1=py311h06a4308_0
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.6=h9b100fa_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxrender=0.9.12=hb9d3cd8_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.3.1=hb25bd0a_0
  - zstd=1.5.7=hb8e6e7a_2
